### ISSUE TITLE
Changing color temperature

### ISSUE THREAD

**Issue by totlol** [jesper-lindberg/homebridge-tradfri#3]
Hi!

Have you considered adding color temperature integration to your plugin?
There is also an other plugin supporting it: https://github.com/szokeptr/homebridge-tradfri-plugin

Thanks

**Comment by jesper-lindberg** [comment]
Hey! Yes, it's on the list. I'm currently thinking about how implement this in the best way. Expect something soonish.

**Comment by tregusti** [comment]
Perhaps it's premature to close this issue since support is not yet added? Please keep it open until the TODO has actually been implemented.
